package CalculatorApp;


/**
* CalculatorApp/DivisionByZero.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Monday, February 23, 2026 6:15:02 AM IST
*/

public final class DivisionByZero extends org.omg.CORBA.UserException
{

  public DivisionByZero ()
  {
    super(DivisionByZeroHelper.id());
  } // ctor


  public DivisionByZero (String $reason)
  {
    super(DivisionByZeroHelper.id() + "  " + $reason);
  } // ctor

} // class DivisionByZero
